blank_issues_enabled: false
contact_links:
  - name: "ğŸ’¡ Suggest a feature"
    url: https://forum.pioneerspacesim.net/
    about: Feature requests and development discussions go on the forum - not on the issue tracker
  - name: "â“ Pioneer FAQ"
    url: https://wiki.pioneerspacesim.net/wiki/FAQ
    about: Others might have had the same question before.
  - name: "â„¹ï¸ Pioneer Manual"
    url: https://wiki.pioneerspacesim.net/wiki/Manual
    about: Manual for the game
  - name: "ğŸš€ Pioneer Flight Manual"
    url: https://wiki.pioneerspacesim.net/wiki/Basic_flight
    about: Manual for flying
  - name: "ğŸ†˜ Get in touch with other players"
    url: https://spacesimcentral.com/community/pioneer/
    about: Community forum is for players sharing
  - name: "ğŸ‘¨â€ğŸ’» Get in touch with developers"
    url: https://kiwiirc.com/client/irc.libera.chat/pioneer
    about: Developers coordinate through IRC (mostly inactive during CET night).
  - name: "ğŸ—£ï¸ Contribute language translation"
    url: https://www.transifex.com/pioneer/pioneer/dashboard/
    about: All translations and language improvements are entirely community driven
